#define BOOST_AUTO_TEST_MAIN
#define BOOST_TEST_MODULE STOPER_YEST_BOOSTOWY

BOOST_AUTO_TEST_SUITE(logger);

BOOST_AUTO_TEST_CASE( sendCustomStruct )
{
    BOOST_CHECK_EQUAL(69, 69);
}

BOOST_AUTO_TEST_SUITE_END();